### ISSUE TITLE
only BREP is supported for geometry representation

### ISSUE THREAD

**Issue by ManoChanda** [opensourceBIM/IfcOpenShell-BIMserver-plugin#3]
I am new to IFC and BIM world, I am using your IfcGeomServer.exe to generate geometry of IFC objects. But your exe only generated values for BREP. If the ifc model does not have brep, it will not generate geometry values. What should I do ? Do you suggest any other Render Engine ? Why there is a dependancy on BREP representation ?

**Comment by rubendel** [comment]
No, it does generate geometry for all kinds of representation. Which representation specifically does not work for you? Do you have an example IFC that illustrates this?

**Comment by ManoChanda** [comment]
can you please see the attached file , I am unable to generate Geometry of this model
[IC_Liberty_Loft7_RDCLogtsv3.zip](https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/files/1437631/IC_Liberty_Loft7_RDCLogtsv3.zip)

**Comment by ManoChanda** [comment]
will you please find some time to see my problem? 
@rubendel  thanking you in advance

**Comment by rubendel** [comment]
It loads just fine here (latest version of everything). Haven't looked at the different types of geometry used, but I assume it's not just breps.

![brep](https://user-images.githubusercontent.com/377978/32485276-1967e576-c3a3-11e7-92bf-e6c8a2b833e5.png)

**Comment by rubendel** [comment]
Oh I am gettings a few errors in the log file I see, not all geometry is converted successfully
```
org.bimserver.plugins.renderengine.RenderEngineException: Exited with non-zero exit code: -1073741571
	at org.ifcopenshell.IfcGeomServerClient.terminate(IfcGeomServerClient.java:496)
	at org.ifcopenshell.IfcGeomServerClient.close(IfcGeomServerClient.java:47)
	at org.ifcopenshell.IfcOpenShellEngine.close(IfcOpenShellEngine.java:77)
	at org.bimserver.renderengine.NoPoolingRenderEnginePool.returnObject(NoPoolingRenderEnginePool.java:40)
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:578)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I have attached one of the smaller "intermediate" files, may @aothms can have a look later?

[IfcWallStandardCase-1.ifc.txt](https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/files/1449309/IfcWallStandardCase-1.ifc.txt)

**Comment by rubendel** [comment]
Possibly related to https://github.com/IfcOpenShell/IfcOpenShell/issues/270 and https://github.com/IfcOpenShell/IfcOpenShell/issues/282

**Comment by ManoChanda** [comment]
thanks for reply, but the exit codes are different, someone reported exit code: 255 and you mentioned -1073741819, and here it was -1073741571

**Comment by rubendel** [comment]
Yeah but I am pretty sure the exit codes are not real exit codes but some sort of overflow.
